### ISSUE TITLE
Is this project maintained any more?

### ISSUE THREAD

**Issue by the94air** [pixinvent/robust-free-bootstrap-admin-template#5]
_No description provided._

**Comment by pixinvent** [comment]
Yes, We do. :)

**Comment by the94air** [comment]
It is awesome how this theme can fill all our need for a basic admin panel. Thank for making it OS with MIT license. But It said in you home page

> We provide life time free updates for our free as well as premium products to our customers.

But I don't see any updates in the lite version as good as the premium version. I mean the last commit was before 6 months. In the mean time.. are you willing to sync the free components with the premium version? thanks again.
